### ISSUE TITLE
Smilei

### ISSUE THREAD

**Issue by iltommi** [wphu/Smilei_SEF#1]
Hi,

I'm one of the developers of the Smilei code.

As you've seen we created (it was time!) a github page for the Smilei code. We have seen all the work you did on the code and we're really amazed about the work you did.

We quickly tried to understand what you did, but it's so huge that I feel better to ask you directly.

Do you have some documentation about the work you did (paper, thesis, reports etc...) so that we can understand better all the physics you added?

Would it be possible to include those publications in the material section of the documentation (https://smileipic.github.io/Smilei/material.html) ?

Would it be possible to include you or you organisation among the partners (https://smileipic.github.io/Smilei/partners.html)

Would you like to collaborate with us to integrate your changes in the latest version of the code?

I think you started to work on one of the first releases of the code.
Since then a lot has changed (the biggest change is the new patch based topology which takes advantage of the mpi/openmp parallelisation and load balancing).

What do you think?

In any case, thanks for the effort and keep Smileing!

Tommaso

p.s. sorry but I realize I don't know your name...

**Comment by wphu** [comment]
Dear Tommaso,
I am very sorry for replying so late, I was busy on other things recently. By the way my name is Hu, Wanpeng, from School of Physics and Optoelectronic Technology, Dalian University of Technology, China.

My main references are [1-3], and the SuperLU library [4] is used to solve the discrete Poisson equation. [5-6] are my two papers, which are done using a fortran code (without particle collisions). Our work is to simulate plasma discharge or plasma sheath. I am doing some works about plasma arc like in ref [7]. I want to add three parts to the SmileI code:

1.	Use SuperLU to solve Poisson equation for 2D case. Plasma discharge is mainly electrostatic problem, therefore, we need solve poisson equaton, rather than Maxwell equations. The direct method is faster than iterative method.

2.	Collisions. For plasma discharge, electrons and ions are mostly from collisions (including impact ionization, charge exchange collision [7]). And elastic collision between neutral atoms is also needed. I do not know whether your new version code (add patchs) can handle the collisions.

3.	Plasma Surface Interaction (PSI). The high energy ions can sputter neutral particles [6] and electrons (SEE) from the material surface. And electrons can be emitted from material if the electric field is very high.

You can include the proper publications in the material section.

Now I have one year left to finish my Ph.D, so I plan to continue doing some developments on the first release. I will like to integrate the changes in the latest version if there are chances in the future.

I am very grateful for your work, and keep Smileing ^^

Wanpeng

[1] Charles K. Birdsall, A. Bruce Langdon, plasma physics via computer simulation; 
[2] R W Hockney, J W Eastwood, computer simulation using particles; 
[3] D. Tskhakaya, K. Matyash, R. Schneider, F. Taccogna, The Particle-In-Cell Method, Contrib. Plasma Phys. 47, 563-594 (2007); 
[4] SuperLU website:  http://crd-legacy.lbl.gov/~xiaoye/SuperLU/;
[5] Wanpeng Hu, Chaofeng Sang, Tengfei Tang, Dezhen Wang, Ming Li, Dazhi Jin, and Xiaohua Tan, Computational study of ion beam extraction phenomena through multiple apertures. Phys. Plasmas 21, 033510 (2014); 
[6] Wanpeng Hu, Chaofeng Sang, Zhenyue Sun, Dezhen Wang, Divertor tungsten tiles erosion in the region of the castellated gaps. Fusion Eng. Des. In Press, available online 7 March 2016; 
[7] H. Timko, K. Matyash, R. Schneider, et al., A One-Dimensional Particle-in-Cell Model of Plasma Build-Up in Vacuum Arcs, Contrib. Plasma Phys. 51 5-21 (2011).
